import os

# The path to OSSID source code
OSSID_ROOT = "/path/to/this/repo" 
# The path to BOP dataset root folder, which contains folder named `lmo` and `ycbv`
BOP_DATASETS_ROOT = "/path/to/bop/datasets"
# Path to bop toolkit source code
BOP_TOOLKIT_PATH = "/path/to/bop_toolkit/source/code"
# Path to a folder where all evaluation results (in BOP format and generated by BOP evaluation script) will be stored
BOP_RESULTS_FOLDER = "/folder/where/results/will/be/saved"
# Path to mAP repo
MAP_CODE_ROOT = "/path/to/mAP/"


'''The following lines should not be changed'''
OSSID_ROOT = os.path.join(OSSID_ROOT, "python", "ossid")
OSSID_CKPT_ROOT = os.path.join(OSSID_ROOT, "ckpts")
OSSID_DATA_ROOT = os.path.join(OSSID_ROOT, "data")
OSSID_RESULT_ROOT = os.path.join(OSSID_ROOT, "scripts/finetune_results")
OSSID_DET_ROOT = os.path.join(OSSID_ROOT, "scripts/det_tmp")